- name: Ensure tools/checkov/reports exists
  file:
    path: "{{ repo_root }}/tools/checkov/reports"
    state: directory

- name: Run terraform action
  include_tasks: "{{ terraform_action }}.yml"
  when: terraform_action is defined
