- hosts: local
  connection: local
  gather_facts: false

  vars:
    repo_root: "{{ lookup('env','WORKSPACE') | default(((playbook_dir ~ '/../..') | realpath), true) }}"
    checkov_soft_fail: "{{ checkov_soft_fail | default(true) }}"

  roles:
    - role: checkov
